version: "3"

services:
  mysite:
    image: wordpress:php7.4-fpm-alpine
    platform: linux/arm64
    restart: unless-stopped
    volumes:
      - ./mysite:/var/www/html
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf
    env_file:
      - .env
    environment:
      WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
      WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
      WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
      WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
    networks:
      - app-network
    depends_on:
      - db
  # Comment db service out if database is deployed somewhere else
  db:
    image: mysql:latest
    platform: linux/arm64
    restart: unless-stopped
    env_file:
      - .env
    command:
      [
        "--default_authentication_plugin=mysql_native_password",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_USER: "${WORDPRESS_DB_USER}"
      MYSQL_DATABASE: "${WORDPRESS_DB_NAME}"
      MYSQL_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    platform: linux/arm64
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./mysite:/mysite:ro
    depends_on:
      - mysite
    networks:
      - app-network
networks:
  app-network:

volumes:
  db_data:
